apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  selector:
    matchLabels:
      app: helloworld
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
      # enter the path to your image, update the 'N' to your demo user
        image: fra.ocir.io/oraseemeatechse/es-repo/kubia:latest
        ports:
        - containerPort: 80
      imagePullSecrets:  
      # enter the name of the secret you created  
      - name:  ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: helloworld
