apiVersion: v1
kind: Service
metadata:
  name: kubia-nodeport
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30123
  selector:
    app: kubia
###
### k create -f https://raw.githubusercontent.com/eugsim1/kubernetes-workshop/master/services/kubia-svc-nodeport.yaml
### k  get svc kubia-nodeport
### kubectl get nodes -o jsonpath='{.items[*].status.addresses[?(@.type=="ExternalIP")].address}'
