apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 1
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: fra.ocir.io/oraseemeatechse/es-repo/kubia:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: ocirsecret
### k create -f         
