apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
  - image: fra.ocir.io/oraseemeatechse/es-repo/kubia:latest
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
  imagePullSecrets:
    - name: ocirsecret
