apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual
spec:
  containers:
  - image: fra.ocir.io/oraseemeatechse/es-repo/kubia:latest
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
  imagePullSecrets:
    - name: ocirsecret 
### k create -f  https://rawhttps://github.com/eugsim1/kubernetes-workshop/
