apiVersion: v1
kind: Pod
metadata:
  name: kubia-gpu
spec:
  nodeSelector:
    gpu: "true"
  containers:
  - image:  fra.ocir.io/oraseemeatechse/es-repo/kubia:latest
    name: kubia
  imagePullSecrets:
    - name: ocirsecret
